marks=[]
f1=input("Enter the first marks: ")
marks.append(f1)
f2=input("Enter the second marks: ")
marks.append(f2)
f3=input("Enter the third marks: ")
marks.append(f3)
f4=input("Enter the fourth marks: ")
marks.append(f4)
f5=input("Enter the fifth marks: ")
marks.append(f5)
f6=input("Enter the sixth marks: ")
marks.append(f6)
marks.sort()
print(marks)